# Generated by Django 4.2.30 on 2026-09-10 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên màu (Tiếng Việt)')),
                ('english_name', models.CharField(blank=True, max_length=100, verbose_name='Tên tiếng Anh')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('hex_code', models.CharField(max_length=20, verbose_name='Mã màu HEX')),
                ('secondary_hex', models.CharField(blank=True, max_length=20, verbose_name='Mã viền/bóng')),
                ('is_dark', models.BooleanField(default=False, verbose_name='Màu tối')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Màu sắc',
                'verbose_name_plural': 'Màu sắc',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=32, unique=True, verbose_name='Mã đơn hàng')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Họ và tên khách hàng')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email nhận hóa đơn')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('shipping_address', models.CharField(max_length=255, verbose_name='Địa chỉ giao hàng')),
                ('province_city', models.CharField(max_length=100, verbose_name='Tỉnh / Thành phố')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Quận / Huyện')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú đơn hàng')),
                ('payment_method', models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng (COD)'), ('vietqr', 'Chuyển khoản VietQR tức thì'), ('apple_pay', 'Apple Pay / Thẻ Quốc Tế'), ('momo', 'Ví MoMo')], default='vietqr', max_length=20, verbose_name='Phương thức thanh toán')),
                ('payment_status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('failed', 'Thất bại')], default='pending', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('status', models.CharField(choices=[('processing', 'Đang xử lý'), ('confirmed', 'Đã xác nhận'), ('shipping', 'Đang giao hàng'), ('delivered', 'Đã giao thành công'), ('cancelled', 'Đã hủy')], default='processing', max_length=20, verbose_name='Trạng thái đơn')),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Phí vận chuyển')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng tiền (VNĐ)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đặt')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên dòng máy')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('generation', models.CharField(default='iPhone 16 Series', max_length=50, verbose_name='Thế hệ')),
                ('screen_size', models.CharField(default='6.1 inch', max_length=50, verbose_name='Kích thước màn hình')),
                ('has_camera_control', models.BooleanField(default=False, verbose_name='Có Nút Điều Khiển Camera')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Dòng máy iPhone',
                'verbose_name_plural': 'Dòng máy iPhone',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='Khẩu hiệu')),
                ('short_description', models.CharField(max_length=500, verbose_name='Mô tả ngắn')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('base_price', models.DecimalField(decimal_places=0, default=1429000, max_digits=12, verbose_name='Giá gốc (VNĐ)')),
                ('badge', models.CharField(blank=True, default='Mới', max_length=50, verbose_name='Huy hiệu')),
                ('is_new', models.BooleanField(default=True, verbose_name='Sản phẩm mới')),
                ('is_featured', models.BooleanField(default=True, verbose_name='Nổi bật')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Tên người đánh giá')),
                ('phone_model_bought', models.CharField(blank=True, max_length=100, verbose_name='Dòng máy đã mua')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Số sao (1-5)')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung đánh giá')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Đã mua hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Mã SKU')),
                ('price', models.DecimalField(decimal_places=0, default=1429000, max_digits=12, verbose_name='Giá bán (VNĐ)')),
                ('stock', models.IntegerField(default=100, verbose_name='Tồn kho')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='Đường dẫn ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kinh doanh')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.color')),
                ('phone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.phonemodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm',
                'verbose_name_plural': 'Biến thể sản phẩm',
                'unique_together': {('product', 'phone_model', 'color')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('phone_model_name', models.CharField(max_length=100)),
                ('color_name', models.CharField(max_length=100)),
                ('color_hex', models.CharField(default='#000000', max_length=20)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productvariant')),
            ],
            options={
                'verbose_name': 'Mục đơn hàng',
                'verbose_name_plural': 'Mục đơn hàng',
            },
        ),
    ]
