# Generated by Django 4.2.30 on 2026-09-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ảnh đại diện sản phẩm'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='https://shopdunk.com/images/thumbs/0020896_black.jpeg'),
        ),
    ]
