# Generated by Django 4.2.30 on 2026-09-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_image_url_alter_productvariant_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Ẩn khỏi giao diện'),
        ),
    ]
