# Generated by Django 4.2.30 on 2026-09-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_color_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_seeded',
            field=models.BooleanField(default=False, verbose_name='Tạo bởi seed (không xóa khi admin thêm)'),
        ),
    ]
