# Generated by Django 4.2.30 on 2026-09-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productvariant_is_seeded'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ảnh swatch/variant URL'),
        ),
    ]
